### ISSUE TITLE
Transpiling two and more C code

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#257] opened 2017-10-21 07:02 UTC
Example:
File `one.c`:
```c
#include "head.h"
int main(){
        say();
        return 0;
}
```
File `head.h`:
```c
void say();
```
File `two.c`:
```c
include<stdio.h>
void say(){
        printf("42");
}
```
Command line for checking in `gcc` - `gcc -c one.c; gcc -c two.c ; gcc -o pr one.o two.o; ./pr`
Result: `42`

Command line for checking `clang` - `clang -E two.c one.c`. Result is like usually.
So, with little modifications of project - we can support a multiply C code transpilation, but now we will have one big single result Go code.

Reason:
*It is need for transpilation of project https://www.cs.cmu.edu/~quake/triangle.html*.

**Comment by elliotchance** [comment] 2017-10-23 04:15
This is a duplicate of #63

**Closed by elliotchance** 2017-10-23 04:15 UTC
