### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Konstantin8105** [elliotchance/c2go#165] opened 2017-06-19 09:26 UTC
Like I understood - for using we have to install `clang`. Could you clarify.

**Comment by elliotchance** [comment] 2017-06-20 00:28
That's correct. On macOS I believe this comes built in. Different linux distributions install clang differently.

Did you need to follow any extra steps to get it working?

**Comment by Konstantin8105** [comment] 2017-06-20 01:45
I use Debian Release 8.8.
Only one - install `clang` and your code help to understood that.
```output
panic: preprocess failed: exec: "clang": executable file not found in $PATH
```
Thanks

**Comment by elliotchance** [comment] 2017-06-20 05:17
Thanks. I'll leave this open to update README to note that clang is required.

**Comment by Konstantin8105** [comment] 2017-06-20 05:40
Just for you. I try to use on Windows.
clang on windows is work.
On more point:
I run `c2go transpile test.c`
The result is:
```result
panic: preprocess failed: exit status 1
goroutine 1 [running]:
main.Check(0x5c9563, 0x13, 0x678a20, 0xc0420023e0)
        Z:/GoPath/src/github.com/elliotchance/c2go/main.go:139 +0xc6
main.Start(0x0, 0xc0420401a7, 0x6, 0x0, 0x0, 0x5c586d, 0x4)
        Z:/GoPath/src/github.com/elliotchance/c2go/main.go:155 +0x25a
main.main()
        Z:/GoPath/src/github.com/elliotchance/c2go/main.go:268 +0x556
```

But after little analyze your code , I run `Z:\GoPath\bin>clang -E test.c`
```result
test.c:1:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
# 1 "test.c"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 300 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "test.c" 2

...
```

In according to that error - we have to have libraries for C.

**Comment by elliotchance** [comment] 2017-06-20 07:16
c2go expects that the code your trying to transpile already compiles successfully with clang. It should give a more helpful message about why the code could not be compiled: https://github.com/elliotchance/c2go/issues/168

**Comment by Konstantin8105** [comment] 2017-06-23 13:23
We have 2 different types of header files:
* System header file, like `<stdio.h>`
* Internal header file, for example `"someLib.h"`

If `clang` don't found the any of header, the `clang`  wrote the `error`. But out transpiling is little bit another.
If `clang` don't found system feader file, then we can ignore that error.
If `clang` don"t found user internal file , then now we can take a `panic()`. Or try to find, but this is only for beta testing multifiles transpiling.

In my point of view, user of transpiling may haven`t all system `C` headers.
I work to multifiles transpiling.

**Comment by Konstantin8105** [comment] 2017-06-23 13:46
So, How it can be?
User enter for example 'c2go transpile test.c',
Then `c2go`: 
* read the source and find all headers from source.
* separate headers to internal and system
* create temp file copy of source, but without headers.
*  analyze temp file like now

**Comment by elliotchance** [comment] 2017-06-24 06:20
You should read this: https://github.com/elliotchance/c2go/wiki/A-Walkthrough-the-Code

Main points:

1. c2go does not parse the C code.
2. The C is preprocessed (so there are no `#include` directives).
3. A system header file and a local header file are the same thing they just come from different locations so if any header file cannot be found clang will error and transpiling in c2go will not be possible.

**Comment by mousse88** [comment] 2017-09-29 17:27
I've a code which succesfully complies with gcc anf clang but produces this error with c2go:

`c2go transpile GMS.C 
panic: clang failed: exit status 1:

In file included from GMS.C:2:
/usr/include/stdio.h:29:8: error: expected identifier or '('
extern "C" {
       ^
GMS.C:10:1: warning: implicitly declaring library function 'printf' with type 'int (const char *, ...)' [-Wimplicit-function-declaration]
printf ("====================================\n");
^
GMS.C:10:1: note: include the header <stdio.h> or explicitly provide a declaration for 'printf'
1 warning and 1 error generated.


goroutine 1 [running]:
panic(0x5e5960, 0xc8200a63a0)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
main.Start(0x0, 0x7ffcd4a69266, 0x5, 0x0, 0x0, 0x689b28, 0x4, 0x0, 0x0, 0x0)
	/home/michel/go/src/github.com/elliotchance/c2go/main.go:202 +0xc10
main.runCommand(0xc820000180)
	/home/michel/go/src/github.com/elliotchance/c2go/main.go:350 +0x50b
main.main()
	/home/michel/go/src/github.com/elliotchance/c2go/main.go:277 +0x18
`
What is wrong ?


gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
c2go version v0.16.2 Radium 2017-09-18

**Comment by elliotchance** [comment] 2017-10-02 09:02
@mousse88 I was able to reproduce the issue locally. The problem is the extension of your source file. `.c` is for C source and `.C` is for C++ code. This is causing clang to parse C++ code as C (since there is no `extern "C"` in C.

**Comment by elliotchance** [comment] 2017-10-02 09:03
I am going to close this ticket now. Please open another ticket if you have any other issues.

**Closed by elliotchance** 2017-10-02 09:03 UTC
Labels: documentation, refactor, small
